# Use root/mypassword as user/password credentials
version: '3.1'

services:

  db_thaochau:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - 9007:3306

  db_tester:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - 9006:3306

  db_dev:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - 9007:3306

  adminer_gui:
    image: adminer
    restart: always
    ports:
      - 9004:8080
