version: '3.1'
services:
  jenkins_custom_service:
    image: jenkinsci/blueocean
    restart: always
    environment:
      JENKINS_USER: root
      JENKINS_PASSWORD: root
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./jenkins-home:/home
    ports:
      - "8080:8080"
    networks:
      - common_network
networks:
    common_network:
      external: true


# Apply Jenkins CI
# User/Pass : root/root
