# Create MySQL Database Server with login information :
# User/Pass : root/root
# Use the common_network with server name : mysql_db_jpa
# Auto execute the SQL file ./database_schema.sql

version: '3'
services:
  gradle_spring_boot:
    build: ./spring-jpa-project
    image: gradle_spring_boot_custom_staging
    environment:
      MYSQL_SERVER: mysql_db_jpa
      MYSQL_SERVER_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      APP_SERVER_PORT: 9222
    volumes:
      # Link Home Gradle folder (between localhost and container)
      - './.gradle_staging:/home/gradle/.gradle'
      # Source folder (using Gradle)
      - './spring-jpa-project:/home/gradle/project'
    ports:
      - "9000:9222"
    depends_on:
      - mysql_db_jpa
    networks:
      - common_network

  mysql_db_jpa:
    image: mariadb:10.3
    container_name: mariadb_for_jpa_springboot
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # SQL Dump file
      - ./mysql_db:/docker-entrypoint-initdb.d
    ports:
      - "3434:3306"
    networks:
      - common_network
networks:
    common_network:
      external: true

